### ISSUE TITLE
CronJobs not updated after operator upgrade

### ISSUE THREAD

**Issue by EFX-PXT1** [hardbyte/netchecks#110]
It seems the CronJobs for a NetworkAssertion are fixed at NetworkAssertion creation time.
It would be ideal if an upgrade of operator or change of configmap resulted in updated CronJobs.
The use-case is where numerous checks are deployed, but a new netchecks image should be used.
It is currently necessary to remove and re-create all of the network assertions to pickup changes.

Best Regards

**Comment by hardbyte** [comment]
Should be addressed by the changes in #113 which is in release `0.5.3`.
