### ISSUE TITLE
Disappearing Policy Reports

### ISSUE THREAD

**Issue by EFX-PXT1** [hardbyte/netchecks#91]
Hi,

I have a NetworkAssertion with a schedule every 5 mins.
It creates a CronJob with successfulJobsHistoryLimit: 3
Upon completion of the Job the operator creates a PolicyReport with 
ownerReference of the probe pod.

The problem is when the owning probe pod drops out of the history
and is deleted, the PolicyReport disappears until the next Job run,

e.g
Policy Report okay (0-15 min elapsed), disappears (15-20 min elapsed), repeat cycle.

Should (can) the operators upsert of PolicyReport be amend to update the ownerReference
to the latest pod to remove the race condition and stop reports disappearing.

Best Regards

**Comment by hardbyte** [comment]
I haven't tried to replicate this issue yet but agree the policy report shouldn't be bound to the probe's lifecycle.

It should be cleaned up when the network assertion is deleted.

Thanks for the bug report.

**Comment by EFX-PXT1** [comment]
Thank you for the exceptionally rapid fix.
I tested the branch fix and the ownership is resolved.

Unfortunately it seems it uncovers  a latent bug where the summary of tests is not correct.
2 tests, one switches to failed, then a subsequent run both pass, but summary has pass:2 fail:1.
Probably previously masked by this now fixed bug.

I will raise a separate issue.

Best Regards.
