### ISSUE TITLE
Incorrect Policy Report Summary

### ISSUE THREAD

**Issue by EFX-PXT1** [hardbyte/netchecks#95]
Hi,

This following issue is observed with - f03f060e9b4a09220c70faa9140452dc8322ff03
for #91 

It would appear not all fields in a PolicyReport Summary are getting correctly updated.
I have 2 tests, both passing generating a summary of pass: 2, fail: 0.
One of the tests fails, logs showing pass: 1, fail: 1.
Which then returns to success, pass: 2, fail 0.
However the policy report summary shows pass: 2, fail 1.

Repeated scheduled runs does not correct the issue.
This was probably masked by deletion of jobs and re-creation of policy reports previously.

Manual deletion of the policy report and upon next job run the summary becomes correct.

Best Regards

**Comment by hardbyte** [comment]
Should be fixed in the 0.5.1 release - please reopen if issue persists after update.

While trying to easily reproduce it gave me the idea for "internal" checks - https://docs.netchecks.io/docs/k8s_data
